### ISSUE TITLE
Current score moves to the left or right when user hovers +1 button

### ISSUE THREAD

**Issue by mcmartincerny** [dcDavidCerny/PingPong#3]
## the problem:
When user hovers over the +1 a new element is shown next to the score with the text `+1?` which shifts the score to the left or to the right.
![image](https://github.com/dcDavidCerny/PingPong/assets/35872038/1d2d7633-5cf1-40bb-9325-f7d70d90dac6)

## proposed fix:
Currently it happens because the element's `style.display` is being set to **none** and **initial** based on the hover.
Which basically changes the position of other elements next to it - the score.
If we would use `element.style.visibility = "hidden"` and `element.style.visibility = "visible"` it would make the element disappear and and appear as needed, but it wouldn't shift the score position.

**Comment by dcDavidCerny** [comment]
Cool, it works this way, thanks for fixing the error.
